# Generated by Django 4.0.2 on 2023-07-20 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('doctor', 'Doctor'), ('accountant', 'Accountant'), ('receptionist', 'Receptionist'), ('pharmacist', 'Pharmacist'), ('pathologist', 'Pathologist'), ('radiologist', 'Radiologist'), ('patient', 'Patient'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_fees', models.FloatField(default=200.0)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='Select', max_length=20)),
                ('appointment_date', models.DateTimeField()),
                ('slot', models.CharField(choices=[('6:00 AM - 9:00 AM', '6:00 AM - 9:00 AM'), ('9:00 AM - 12:00 PM', '9:00 AM - 12:00 PM'), ('12:00 PM - 3:00 PM', '12:00 PM - 3:00 PM'), ('3:00 PM - 6:00 PM', '3:00 PM - 6:00 PM'), ('6:00 PM - 9:00 PM', '6:00 PM - 9:00 PM'), ('9:00 PM - 12:00 AM', '9:00 PM - 12:00 AM')], default='Select', max_length=20)),
                ('appointment_priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('very urgent', 'Very Urgent'), ('low', 'Low')], default='Normal', max_length=20)),
                ('payment_mode', models.CharField(choices=[('select', 'Select'), ('pending', 'Pending'), ('approved', 'Approved'), ('cancel', 'Cancel')], default='Select', max_length=40)),
                ('message', models.TextField()),
                ('live_consultant', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='Select', max_length=10)),
                ('alternate_address', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
