# Generated by Django 4.0.2 on 2023-07-21 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_patient_age_patient_day_patient_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bp', models.FloatField()),
                ('pulse', models.FloatField()),
                ('temperature', models.FloatField()),
                ('respiration', models.FloatField()),
                ('symptoms_type', models.CharField(choices=[('select', 'Select'), ('eating or weight problems', 'Eating or weight problems'), ('emotional problems', 'Emotional problems'), ('muscle or joint problems', 'Muscle or joint problems'), ('skin problems', 'Skin problems'), ('bladder problems', 'Bladder problems'), ('stomach problems', 'Stomach problems'), ('lung problems', 'Lung problems')], default='select', max_length=40)),
                ('symptoms_title', models.CharField(max_length=100)),
                ('symptoms_description', models.TextField()),
                ('note', models.TextField()),
                ('any_known_allergies', models.TextField()),
                ('previous_medical_issue', models.TextField()),
                ('appointment_date', models.DateTimeField()),
                ('case', models.CharField(max_length=100)),
                ('casualty', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=40)),
                ('old_patient', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=40)),
                ('TPA', models.CharField(choices=[('select', 'Select'), ('health life insurance', 'Health Life Insurance'), ('star health insurance', 'Star Health Insurance'), ('idbi fedral', 'IDBI Federal'), ('cghs', 'CGHS')], default='Select', max_length=40)),
                ('reference', models.CharField(max_length=50)),
                ('charge_category', models.CharField(choices=[('select', 'Select'), ('OPD consultaion fees', 'OPD Consultaion Fees'), ('OPD service', 'OPD Service'), ('OPD insurance', 'OPD Insurance'), ('blood pressure check', 'Blood Pressure Check'), ('eye check', 'Eye Check'), ('cholesterol level check', 'Cholesterol level check'), ('sterilization and cleaning equipment', 'Sterilization and Cleaning Equipment'), ('oxygen cylinder', 'Oxygen cylinder'), ('fire extinguisher', 'Fire extinguisher'), ('operation services', 'Operation Services'), ('other charges', 'Other Charges')], default='Select', max_length=40)),
                ('tax', models.FloatField()),
                ('standard_charge', models.FloatField()),
                ('applied_charge', models.FloatField()),
                ('amount', models.FloatField()),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('transfer to bank account', 'Transfer To Bank Account'), ('upi', 'UPI'), ('other', 'Other'), ('online', 'Online')], default='Cash', max_length=30)),
                ('paid_amount', models.FloatField()),
                ('live_consultation', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=30)),
                ('consultant_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
