# Generated by Django 4.0.2 on 2023-07-21 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_outpatient'),
    ]

    operations = [
        migrations.CreateModel(
            name='InPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bp', models.FloatField()),
                ('pulse', models.FloatField()),
                ('temperature', models.FloatField()),
                ('respiration', models.FloatField()),
                ('symptoms_type', models.CharField(choices=[('select', 'Select'), ('eating or weight problems', 'Eating or weight problems'), ('emotional problems', 'Emotional problems'), ('muscle or joint problems', 'Muscle or joint problems'), ('skin problems', 'Skin problems'), ('bladder problems', 'Bladder problems'), ('stomach problems', 'Stomach problems'), ('lung problems', 'Lung problems')], default='select', max_length=40)),
                ('symptoms_title', models.CharField(max_length=100)),
                ('symptoms_description', models.TextField()),
                ('note', models.TextField()),
                ('previous_medical_issue', models.TextField()),
                ('admission_date', models.DateTimeField()),
                ('case', models.CharField(max_length=100)),
                ('casualty', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=40)),
                ('old_patient', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=40)),
                ('TPA', models.CharField(choices=[('select', 'Select'), ('health life insurance', 'Health Life Insurance'), ('star health insurance', 'Star Health Insurance'), ('idbi fedral', 'IDBI Federal'), ('cghs', 'CGHS')], default='Select', max_length=40)),
                ('credit_limit', models.FloatField(default=20000)),
                ('reference', models.CharField(max_length=50)),
                ('bed_group', models.CharField(choices=[('select', 'Select'), ('VIP ward-ground floor', 'VIP Ward-Ground Floor'), ('Private ward-3rd floor', 'Private Ward-3rd Floor'), ('General ward male-3rd floor', 'General Ward Male-3rd Floor'), ('Private ward-3rd floor', 'Private Ward-3rd Floor'), ('ICU-2nd floor', 'ICU-2nd Floor'), ('NICU-2nd floor', 'NICU-2nd Floor'), ('AC(normal)-1st floor', 'AC(Normal)-1st Floor'), ('Non AC-4th floor', 'Non AC-4th Floor')], default='Select', max_length=40)),
                ('bed_number', models.CharField(choices=[('select', 'Select')], default='Select', max_length=30)),
                ('live_consultation', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=30)),
                ('consultant_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
