# Generated by Django 4.0.2 on 2023-07-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_inpatient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('medicine_category', models.CharField(choices=[('select', 'Select'), ('syrup', 'Syrup'), ('capsule', 'Capsule'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('cream', 'Cream'), ('surgical', 'Surgical'), ('drops', 'Drops'), ('inhalers', 'Inhalers'), ('implants/patches', 'Implants/Patches'), ('liquid', 'Liquid'), ('preparations', 'Preparations'), ('diaper', 'Diaper'), ('tablet', 'Tablet')], default='Select', max_length=100)),
                ('medicine_company', models.CharField(max_length=100)),
                ('medicine_composition', models.CharField(max_length=100)),
                ('medicine_group', models.CharField(max_length=100)),
                ('unit', models.PositiveIntegerField()),
                ('min_level', models.PositiveIntegerField()),
                ('re_order_level', models.PositiveIntegerField()),
                ('tax', models.FloatField()),
                ('unit_packing', models.PositiveIntegerField()),
                ('vat_ac', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('medicine_photo', models.FileField(upload_to='images/medicine/')),
            ],
        ),
        migrations.CreateModel(
            name='PathologyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('test_type', models.CharField(max_length=100)),
                ('category_name', models.CharField(choices=[('select', 'Select'), ('clinical microbiology', 'Clinical Microbiology'), ('clinical chemistry', 'Clinical Chemistry'), ('hematology', 'Hematology'), ('molecular diagnostics', 'Molecular Diagnostics'), ('reproductive biology', 'Reproductive Biology'), ('electromagnetic waves', 'Electromagnetic Waves')], default='Select', max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('report_days', models.PositiveIntegerField()),
                ('charge_category', models.CharField(choices=[('select', 'Select'), ('surgical pathology', 'Surgical Pathology'), ('histopathology', 'Histopathology'), ('cytopathology', 'Cytopathology'), ('forensic pathology', 'Forensic pathology'), ('dermatopathology', 'Dermatopathology'), ('x-ray', 'X-Ray'), ('other charges', 'Other Charges')], default='Select', max_length=100)),
                ('tax', models.FloatField(default='30.00')),
                ('standard_charge', models.FloatField(default='160.00')),
                ('amount', models.FloatField(default='208.00')),
            ],
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_parameter_name', models.CharField(choices=[('select', 'Select'), ('rbc', 'RBC'), ('liver function test', 'Liver Function Test'), ('tsh(thyroid stimulation hormone)', 'TSH(Thyroid Stimulation Hormone)')], default='Select', max_length=100)),
                ('reference_range', models.CharField(editable=False, max_length=40)),
                ('unit', models.CharField(editable=False, max_length=40)),
                ('pathology_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='account.pathologytest')),
            ],
        ),
    ]
