# Generated by Django 4.0.2 on 2023-07-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_medicine_pathologytest_testparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('d_o_b', models.DateField()),
                ('blood_donor', models.CharField(choices=[('select', 'Select'), ('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='Select', max_length=20)),
                ('gender', models.CharField(choices=[('select', 'Select'), ('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], default='Select', max_length=20)),
                ('father_name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
