# Generated by Django 4.0.2 on 2023-07-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_cryo_bag_alter_cryo_institution_alter_cryo_lot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=40)),
                ('vehicle_model', models.CharField(max_length=40)),
                ('year_made', models.CharField(max_length=10)),
                ('driver_name', models.CharField(max_length=40)),
                ('driver_license', models.CharField(max_length=40)),
                ('driver_contact', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('select', 'Select'), ('owner', 'Owner'), ('contractual', 'Contractual')], default='Select', max_length=40)),
                ('note', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='components',
            name='bag',
            field=models.CharField(choices=[('select', 'Select'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='Select', max_length=20),
        ),
    ]
