# Generated by Django 4.0.2 on 2023-07-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_ambulance_alter_components_bag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('select', 'Select'), ('visit', 'Visit'), ('enquiry', 'Enquiry'), ('seminar', 'Seminar')], default='Select', max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('id_card', models.CharField(max_length=40)),
                ('visit_to', models.CharField(choices=[('select', 'Select'), ('staff', 'Staff'), ('opd patient', 'OPD Patient'), ('ipd patient', 'IPD Patient')], default='Select', max_length=40)),
                ('related_to', models.CharField(max_length=40)),
                ('number_of_person', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('note', models.TextField()),
                ('document', models.FileField(upload_to='images/visitor/')),
            ],
        ),
    ]
