# Generated by Django 4.0.2 on 2023-07-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('nextdate', models.DateField()),
                ('call_duration', models.CharField(max_length=40)),
                ('note', models.TextField()),
                ('call_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
            ],
        ),
    ]
