# Generated by Django 4.0.2 on 2023-07-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_calllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('select', 'Select'), ('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], default='Select', max_length=20)),
                ('weight', models.CharField(max_length=40)),
                ('child_photo', models.ImageField(upload_to='images/child/')),
                ('date_of_birth', models.DateTimeField()),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('case_id', models.CharField(max_length=40)),
                ('mother_name', models.CharField(max_length=40)),
                ('mother_photo', models.ImageField(upload_to='images/mother/')),
                ('father_name', models.CharField(max_length=40)),
                ('father_photo', models.ImageField(upload_to='images/father/')),
                ('report', models.TextField()),
                ('document_photo', models.ImageField(upload_to='images/document/')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_type', models.CharField(choices=[('select', 'Select'), ('food quality', 'Food Quality'), ('hospital services', 'Hospital Services'), ('long wait times', 'Long Wait Times'), ('billing discrepancies', 'Billing Discrepancies')], default='Select', max_length=40)),
                ('source', models.CharField(choices=[('select', 'Select'), ('online advertising', 'Online Advertising'), ('from visitors', 'From Visitors'), ('front office', 'Front Office')], default='Select', max_length=20)),
                ('complain_by', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('action_taken', models.CharField(max_length=40)),
                ('assigned', models.CharField(max_length=40)),
                ('note', models.TextField()),
                ('document', models.FileField(upload_to='images/complain/')),
            ],
        ),
        migrations.CreateModel(
            name='DeathRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=40)),
                ('patient_name', models.CharField(max_length=40)),
                ('death_date', models.DateTimeField()),
                ('guardian_name', models.CharField(max_length=40)),
                ('attachment', models.ImageField(upload_to='images/attachment/')),
                ('report', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_title', models.CharField(max_length=40)),
                ('reference_no', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('note', models.TextField()),
                ('from_title', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('document', models.FileField(upload_to='images/postal/dispatch/')),
            ],
        ),
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_title', models.CharField(max_length=40)),
                ('reference_no', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('note', models.TextField()),
                ('to_title', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('document', models.FileField(upload_to='images/postal/receive/')),
            ],
        ),
    ]
