# Generated by Django 4.0.2 on 2023-07-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_income_tpa_alter_birthrecord_child_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatient',
            name='TPA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.tpa'),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='TPA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.tpa'),
        ),
    ]
