# Generated by Django 4.0.2 on 2023-07-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_inpatient_tpa_alter_outpatient_tpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/patient/'),
        ),
    ]
