# Generated by Django 4.0.2 on 2023-07-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_patient_patient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='vehicle_type',
            field=models.CharField(choices=[('select', 'Select'), ('owner', 'Owner'), ('contractual', 'Contractual')], default='select', max_length=40),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('very urgent', 'Very Urgent'), ('low', 'Low')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='live_consultant',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='select', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_mode',
            field=models.CharField(choices=[('select', 'Select'), ('pending', 'Pending'), ('approved', 'Approved'), ('cancel', 'Cancel')], default='select', max_length=40),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.CharField(choices=[('6:00 AM - 9:00 AM', '6:00 AM - 9:00 AM'), ('9:00 AM - 12:00 PM', '9:00 AM - 12:00 PM'), ('12:00 PM - 3:00 PM', '12:00 PM - 3:00 PM'), ('3:00 PM - 6:00 PM', '3:00 PM - 6:00 PM'), ('6:00 PM - 9:00 PM', '6:00 PM - 9:00 PM'), ('9:00 PM - 12:00 AM', '9:00 PM - 12:00 AM')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='gender',
            field=models.CharField(choices=[('select', 'Select'), ('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='complain_type',
            field=models.CharField(choices=[('select', 'Select'), ('food quality', 'Food Quality'), ('hospital services', 'Hospital Services'), ('long wait times', 'Long Wait Times'), ('billing discrepancies', 'Billing Discrepancies')], default='select', max_length=40),
        ),
        migrations.AlterField(
            model_name='complain',
            name='source',
            field=models.CharField(choices=[('select', 'Select'), ('online advertising', 'Online Advertising'), ('from visitors', 'From Visitors'), ('front office', 'Front Office')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='cryo',
            name='unit',
            field=models.CharField(choices=[('select', 'Select'), ('ml', 'ML'), ('litter', 'Litter'), ('mm', 'MM'), ('day', 'Day'), ('hour', 'Hour'), ('insurance', 'Insurance'), ('-', '-'), ('mg', 'MG')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='cryodot',
            name='unit',
            field=models.CharField(choices=[('select', 'Select'), ('ml', 'ML'), ('litter', 'Litter'), ('mm', 'MM'), ('day', 'Day'), ('hour', 'Hour'), ('insurance', 'Insurance'), ('-', '-'), ('mg', 'MG')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_head',
            field=models.CharField(choices=[('select', 'Select'), ('hospital charges', 'Hospital Charges'), ('special campaign', 'Special Campaign'), ('canteen rent', 'Canteen Rent'), ('vehicle stand charges', 'Vehicle Stand Charges')], default='select', max_length=60),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('select', 'Select'), ('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='select', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('select', 'Select'), ('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('select', 'Select'), ('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('not specified', 'Not Specified')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='plasma',
            name='unit',
            field=models.CharField(choices=[('select', 'Select'), ('ml', 'ML'), ('litter', 'Litter'), ('mm', 'MM'), ('day', 'Day'), ('hour', 'Hour'), ('insurance', 'Insurance'), ('-', '-'), ('mg', 'MG')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='platelets',
            name='unit',
            field=models.CharField(choices=[('select', 'Select'), ('ml', 'ML'), ('litter', 'Litter'), ('mm', 'MM'), ('day', 'Day'), ('hour', 'Hour'), ('insurance', 'Insurance'), ('-', '-'), ('mg', 'MG')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='redcells',
            name='unit',
            field=models.CharField(choices=[('select', 'Select'), ('ml', 'ML'), ('litter', 'Litter'), ('mm', 'MM'), ('day', 'Day'), ('hour', 'Hour'), ('insurance', 'Insurance'), ('-', '-'), ('mg', 'MG')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.CharField(choices=[('select', 'Select'), ('visit', 'Visit'), ('enquiry', 'Enquiry'), ('seminar', 'Seminar')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_to',
            field=models.CharField(choices=[('select', 'Select'), ('staff', 'Staff'), ('opd patient', 'OPD Patient'), ('ipd patient', 'IPD Patient')], default='select', max_length=40),
        ),
        migrations.AlterField(
            model_name='whitecells',
            name='unit',
            field=models.CharField(choices=[('select', 'Select'), ('ml', 'ML'), ('litter', 'Litter'), ('mm', 'MM'), ('day', 'Day'), ('hour', 'Hour'), ('insurance', 'Insurance'), ('-', '-'), ('mg', 'MG')], default='select', max_length=20),
        ),
    ]
