# Generated by Django 4.0.2 on 2023-08-04 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_alter_referralcommission_ambulance_and_more'),
        ('account', '0021_remove_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_leaves', models.PositiveIntegerField(default=0)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.leavetype')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='leaves',
            field=models.ManyToManyField(through='account.StaffLeave', to='settings.LeaveType'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('accountant', 'Accountant'), ('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('radiologist', 'Radiologist'), ('pathologist', 'Pathologist'), ('superadmin', 'Super Admin'), ('receptionist', 'Receptionist'), ('nurse', 'Nurse')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialist',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffleave',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
