# Generated by Django 4.0.2 on 2023-08-04 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_alter_referralcommission_ambulance_and_more'),
        ('account', '0023_remove_customuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.medicinecategory'),
        ),
        migrations.CreateModel(
            name='PurchaseMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=20)),
                ('expiry_date', models.DateField()),
                ('mrp', models.FloatField()),
                ('batch_amount', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('packing_qty', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.FloatField()),
                ('tax', models.PositiveIntegerField(editable=False)),
                ('amount', models.FloatField()),
                ('medicine_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.medicinecategory')),
                ('medicine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.medicine')),
            ],
        ),
    ]
