# Generated by Django 4.0.2 on 2023-08-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_medicine_medicine_category_purchasemedicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemedicine',
            name='tax',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
