# Generated by Django 4.0.2 on 2023-08-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_item_alter_appointment_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralperson',
            name='commission',
            field=models.CharField(max_length=100),
        ),
    ]
