# Generated by Django 4.0.2 on 2023-08-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_referralperson_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthrecord',
            name='child_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/birthrecord/child/'),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='document_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/birthrecord/document/'),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='father_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/birthrecord/father/'),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='mother_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/birthrecord/mother/'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='images/complain/'),
        ),
        migrations.AlterField(
            model_name='deathrecord',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='images/deathrecord/'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='images/postal/dispatch/'),
        ),
        migrations.AlterField(
            model_name='income',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='images/income/'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='images/itemstock/'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_photo',
            field=models.FileField(blank=True, null=True, upload_to='images/medicine/'),
        ),
        migrations.AlterField(
            model_name='receive',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='images/postal/receive/'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='images/visitor/'),
        ),
    ]
