# Generated by Django 4.0.2 on 2023-08-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_alter_referralcommission_ambulance_and_more'),
        ('account', '0028_alter_birthrecord_child_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('document', models.ImageField(blank=True, null=True, upload_to='images/expense/')),
                ('description', models.TextField()),
                ('expense_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.expensehead')),
            ],
        ),
    ]
