from django.contrib import admin
from .models import *

admin.site.register(UnitType)
admin.site.register(TaxCategory)
admin.site.register(ChargeType)
admin.site.register(ChargeCategory)
admin.site.register(Charges)
admin.site.register(Floor)
admin.site.register(BedType)
admin.site.register(BedGroup)
admin.site.register(Bed)
admin.site.register(Priority)
admin.site.register(Source)
admin.site.register(ComplainType)
admin.site.register(Purpose)
admin.site.register(OperationCategory)
admin.site.register(Operation)
admin.site.register(MedicineDosage)
admin.site.register(DosageInterval)
admin.site.register(DosageDuration)
admin.site.register(PathologyCategory)
admin.site.register(PathologyUnit)
admin.site.register(PathologyParameter)
admin.site.register(RadiologyCategory)
admin.site.register(RadiologyUnit)
admin.site.register(RadiologyParameter)
admin.site.register(BloodBank_Products)
admin.site.register(SymptomsType)
admin.site.register(SymptomsHead)