from django.urls import path, include
from settings.views import *

urlpatterns = [
    path('api/create-unittype/', UnittypeCreateAPIView.as_view(), name='create_unittype'),
    path('api/unittype/', UnittypeListView.as_view(), name='unittype-list'),
    path('api/unittypes/<int:pk>/', UnitTypeUpdateView.as_view(), name='unittype-update'),
    path('api/unittypes/<int:pk>/delete/', UnitTypeDeleteView.as_view(), name='unittype-delete'),
    path('api/unittypes/<int:pk>/detail/', UnitTypeDetailView.as_view(), name='unittype-detail'),
    
    path('api/create-taxcategory/', TaxCategoryCreateAPIView.as_view(), name='create_taxcategory'),
    path('api/taxcategory/', TaxCategoryListView.as_view(), name='taxcategory-list'),
    path('api/taxcategory/<int:pk>/', TaxCategoryUpdateView.as_view(), name='taxcategory-update'),
    path('api/taxcategory/<int:pk>/delete/', TaxCategoryDeleteView.as_view(), name='taxcategory-delete'),
    path('api/taxcategory/<int:pk>/detail/', TaxCategoryDetailView.as_view(), name='taxcategory-detail'),
    
    path('api/create-chargetype/', ChargeTypeCreateAPIView.as_view(), name='create_chargetype'),
    path('api/chargetype/', ChargeTypeListView.as_view(), name='chargetype-list'),
    path('api/chargetype/<int:pk>/', ChargeTypeUpdateView.as_view(), name='chargetype-update'),
    path('api/chargetype/<int:pk>/delete/', ChargeTypeDeleteView.as_view(), name='chargetype-delete'),
    path('api/chargetype/<int:pk>/detail/', ChargeTypeDetailView.as_view(), name='chargetype-detail'),
    
    path('api/create-chargecategory/', ChargeCategoryCreateAPIView.as_view(), name='create_chargecategory'),
    path('api/chargecategory/', ChargeCategoryListView.as_view(), name='chargecategory-list'),
    path('api/chargecategory/<int:pk>/', ChargeCategoryUpdateView.as_view(), name='chargecategory-update'),
    path('api/chargecategory/<int:pk>/delete/', ChargeCategoryDeleteView.as_view(), name='chargecategory-delete'),
    path('api/chargecategory/<int:pk>/detail/', ChargeCategoryDetailView.as_view(), name='chargecategory-detail'),
    
    path('api/create-charges/', ChargesCreateAPIView.as_view(), name='create_charges'),
    path('api/charges/', ChargesListView.as_view(), name='charges-list'),
    path('api/charges/<int:pk>/', ChargesUpdateView.as_view(), name='charges-update'),
    path('api/charges/<int:pk>/delete/', ChargesDeleteView.as_view(), name='charges-delete'),
    path('api/charges/<int:pk>/detail/', ChargesDetailView.as_view(), name='charges-detail'),
    
    path('api/create-floor/', FloorCreateAPIView.as_view(), name='create_floor'),
    path('api/floor/', FloorListView.as_view(), name='floor-list'),
    path('api/floor/<int:pk>/', FloorUpdateView.as_view(), name='floor-update'),
    path('api/floor/<int:pk>/delete/', FloorDeleteView.as_view(), name='floor-delete'),
    path('api/floor/<int:pk>/detail/', FloorDetailView.as_view(), name='floor-detail'),
    
    path('api/create-bedtype/', BedTypeCreateAPIView.as_view(), name='create_bedtype'),
    path('api/bedtype/', BedTypeListView.as_view(), name='bedtype-list'),
    path('api/bedtype/<int:pk>/', BedTypeUpdateView.as_view(), name='bedtype-update'),
    path('api/bedtype/<int:pk>/delete/', BedTypeDeleteView.as_view(), name='bedtype-delete'),
    path('api/bedtype/<int:pk>/detail/', BedTypeDetailView.as_view(), name='bedtype-detail'),
    
    path('api/create-bedgroup/', BedGroupCreateAPIView.as_view(), name='create_bedgroup'),
    path('api/bedgroup/', BedGroupListView.as_view(), name='bedgroup-list'),
    path('api/bedgroup/<int:pk>/', BedGroupUpdateView.as_view(), name='bedgroup-update'),
    path('api/bedgroup/<int:pk>/delete/', BedGroupDeleteView.as_view(), name='bedgroup-delete'),
    path('api/bedgroup/<int:pk>/detail/', BedGroupDetailView.as_view(), name='bedgroup-detail'),
    
    path('api/create-bed/', BedCreateAPIView.as_view(), name='create_bed'),
    path('api/bed/', BedListView.as_view(), name='bed-list'),
    path('api/bed/<int:pk>/', BedUpdateView.as_view(), name='bed-update'),
    path('api/bed/<int:pk>/delete/', BedDeleteView.as_view(), name='bed-delete'),
    path('api/bed/<int:pk>/detail/', BedDetailView.as_view(), name='bed-detail'),
    
    path('api/create-priority/', PriorityCreateAPIView.as_view(), name='create_priority'),
    path('api/priority/', PriorityListView.as_view(), name='priority-list'),
    path('api/priority/<int:pk>/', PriorityUpdateView.as_view(), name='priority-update'),
    path('api/priority/<int:pk>/delete/', PriorityDeleteView.as_view(), name='priority-delete'),
    path('api/priority/<int:pk>/detail/', PriorityDetailView.as_view(), name='priority-detail'),
    
    path('api/create-source/', SourceCreateAPIView.as_view(), name='create_source'),
    path('api/source/', SourceListView.as_view(), name='source-list'),
    path('api/source/<int:pk>/', SourceUpdateView.as_view(), name='source-update'),
    path('api/source/<int:pk>/delete/', SourceDeleteView.as_view(), name='source-delete'),
    path('api/source/<int:pk>/detail/', SourceDetailView.as_view(), name='source-detail'),
    
    path('api/create-complaintype/', ComplainTypeCreateAPIView.as_view(), name='create_complaintype'),
    path('api/complaintype/', ComplainTypeListView.as_view(), name='complaintype-list'),
    path('api/complaintype/<int:pk>/', ComplainTypeUpdateView.as_view(), name='complaintype-update'),
    path('api/complaintype/<int:pk>/delete/', ComplainTypeDeleteView.as_view(), name='complaintype-delete'),
    path('api/complaintype/<int:pk>/detail/', ComplainTypeDetailView.as_view(), name='complaintype-detail'),
    
    path('api/create-purpose/', PurposeCreateAPIView.as_view(), name='create_purpose'),
    path('api/purpose/', PurposeListView.as_view(), name='purpose-list'),
    path('api/purpose/<int:pk>/', PurposeUpdateView.as_view(), name='purpose-update'),
    path('api/purpose/<int:pk>/delete/', PurposeDeleteView.as_view(), name='purpose-delete'),
    path('api/purpose/<int:pk>/detail/', PurposeDetailView.as_view(), name='purpose-detail'),
    
    path('api/create-operationcategory/', OperationCategoryCreateAPIView.as_view(), name='create_operationcategory'),
    path('api/operationcategory/', OperationCategoryListView.as_view(), name='operationcategory-list'),
    path('api/operationcategory/<int:pk>/', OperationCategoryUpdateView.as_view(), name='operationcategory-update'),
    path('api/operationcategory/<int:pk>/delete/', OperationCategoryDeleteView.as_view(), name='operationcategory-delete'),
    path('api/operationcategory/<int:pk>/detail/', OperationCategoryDetailView.as_view(), name='operationcategory-detail'),
    
    path('api/create-operation/', OperationCreateAPIView.as_view(), name='create_operation'),
    path('api/operation/', OperationListView.as_view(), name='operation-list'),
    path('api/operation/<int:pk>/', OperationUpdateView.as_view(), name='operation-update'),
    path('api/operation/<int:pk>/delete/', OperationDeleteView.as_view(), name='operation-delete'),
    path('api/operation/<int:pk>/detail/', OperationDetailView.as_view(), name='operation-detail'),
    
    path('api/create-medicinecategory/', MedicineCategoryCreateAPIView.as_view(), name='create_medicinecategory'),
    path('api/medicinecategory/', MedicineCategoryListView.as_view(), name='medicinecategory-list'),
    path('api/medicinecategory/<int:pk>/', MedicineCategoryUpdateView.as_view(), name='medicinecategory-update'),
    path('api/medicinecategory/<int:pk>/delete/', MedicineCategoryDeleteView.as_view(), name='medicinecategory-delete'),
    path('api/medicinecategory/<int:pk>/detail/', MedicineCategoryDetailView.as_view(), name='medicinecategory-detail'),
    
    path('api/create-medicinesupplier/', MedicineSupplierCreateAPIView.as_view(), name='create_medicinesupplier'),
    path('api/medicinesupplier/', MedicineSupplierListView.as_view(), name='medicinesupplier-list'),
    path('api/medicinesupplier/<int:pk>/', MedicineSupplierUpdateView.as_view(), name='medicinesupplier-update'),
    path('api/medicinesupplier/<int:pk>/delete/', MedicineSupplierDeleteView.as_view(), name='medicinesupplier-delete'),
    path('api/medicinesupplier/<int:pk>/detail/', MedicineSupplierDetailView.as_view(), name='medicinesupplier-detail'),
    
    path('api/create-medicinedosage/', MedicineDosageCreateAPIView.as_view(), name='create_medicinedosage'),
    path('api/medicinedosage/', MedicineDosageListView.as_view(), name='medicinedosage-list'),
    path('api/medicinedosage/<int:pk>/', MedicineDosageUpdateView.as_view(), name='medicinedosage-update'),
    path('api/medicinedosage/<int:pk>/delete/', MedicineDosageDeleteView.as_view(), name='medicinedosage-delete'),
    path('api/medicinedosage/<int:pk>/detail/', MedicineDosageDetailView.as_view(), name='medicinedosage-detail'),

    path('api/create-dosageinterval/', DosageIntervalCreateAPIView.as_view(), name='create_dosageinterval'),
    path('api/dosageinterval/', DosageIntervalListView.as_view(), name='dosageinterval-list'),
    path('api/dosageinterval/<int:pk>/', DosageIntervalUpdateView.as_view(), name='dosageinterval-update'),
    path('api/dosageinterval/<int:pk>/delete/', DosageIntervalDeleteView.as_view(), name='dosageinterval-delete'),
    path('api/dosageinterval/<int:pk>/detail/', DosageIntervalDetailView.as_view(), name='dosageinterval-detail'),
    
    path('api/create-dosageduration/', DosageDurationCreateAPIView.as_view(), name='create_dosageduration'),
    path('api/dosageduration/', DosageDurationListView.as_view(), name='dosageduration-list'),
    path('api/dosageduration/<int:pk>/', DosageDurationUpdateView.as_view(), name='dosageduration-update'),
    path('api/dosageduration/<int:pk>/delete/', DosageDurationDeleteView.as_view(), name='dosageduration-delete'),
    path('api/dosageduration/<int:pk>/detail/', DosageDurationDetailView.as_view(), name='dosageduration-detail'),
    
    path('api/create-pathologycategory/', PathologyCategoryCreateAPIView.as_view(), name='create_pathologycategory'),
    path('api/pathologycategory/', PathologyCategoryListView.as_view(), name='pathologycategory-list'),
    path('api/pathologycategory/<int:pk>/', PathologyCategoryUpdateView.as_view(), name='pathologycategory-update'),
    path('api/pathologycategory/<int:pk>/delete/', PathologyCategoryDeleteView.as_view(), name='pathologycategory-delete'),
    path('api/pathologycategory/<int:pk>/detail/', PathologyCategoryDetailView.as_view(), name='pathologycategory-detail'),

    path('api/create-pathologyunit/', PathologyUnitCreateAPIView.as_view(), name='create_pathologyunit'),
    path('api/pathologyunit/', PathologyUnitListView.as_view(), name='pathologyunit-list'),
    path('api/pathologyunit/<int:pk>/', PathologyUnitUpdateView.as_view(), name='pathologyunit-update'),
    path('api/pathologyunit/<int:pk>/delete/', PathologyUnitDeleteView.as_view(), name='pathologyunit-delete'),
    path('api/pathologyunit/<int:pk>/detail/', PathologyUnitDetailView.as_view(), name='pathologyunit-detail'),
    
    path('api/create-pathologyparameter/', PathologyParameterCreateAPIView.as_view(), name='create_pathologyparameter'),
    path('api/pathologyparameter/', PathologyParameterListView.as_view(), name='pathologyparameter-list'),
    path('api/pathologyparameter/<int:pk>/', PathologyParameterUpdateView.as_view(), name='pathologyparameter-update'),
    path('api/pathologyparameter/<int:pk>/delete/', PathologyParameterDeleteView.as_view(), name='pathologyparameter-delete'),
    path('api/pathologyparameter/<int:pk>/detail/', PathologyParameterDetailView.as_view(), name='pathologyparameter-detail'),
    
    path('api/create-radiologycategory/', RadiologyCategoryCreateAPIView.as_view(), name='create_radiologycategory'),
    path('api/radiologycategory/', RadiologyCategoryListView.as_view(), name='radiologycategory-list'),
    path('api/radiologycategory/<int:pk>/', RadiologyCategoryUpdateView.as_view(), name='radiologycategory-update'),
    path('api/radiologycategory/<int:pk>/delete/', RadiologyCategoryDeleteView.as_view(), name='radiologycategory-delete'),
    path('api/radiologycategory/<int:pk>/detail/', RadiologyCategoryDetailView.as_view(), name='radiologycategory-detail'),

    path('api/create-radiologyunit/', RadiologyUnitCreateAPIView.as_view(), name='create_radiologyunit'),
    path('api/radiologyunit/', RadiologyUnitListView.as_view(), name='radiologyunit-list'),
    path('api/radiologyunit/<int:pk>/', RadiologyUnitUpdateView.as_view(), name='radiologyunit-update'),
    path('api/radiologyunit/<int:pk>/delete/', RadiologyUnitDeleteView.as_view(), name='radiologyunit-delete'),
    path('api/radiologyunit/<int:pk>/detail/', RadiologyUnitDetailView.as_view(), name='radiologyunit-detail'),
    
    path('api/create-radiologyparameter/', RadiologyParameterCreateAPIView.as_view(), name='create_radiologyparameter'),
    path('api/radiologyparameter/', RadiologyParameterListView.as_view(), name='radiologyparameter-list'),
    path('api/radiologyparameter/<int:pk>/', RadiologyParameterUpdateView.as_view(), name='radiologyparameter-update'),
    path('api/radiologyparameter/<int:pk>/delete/', RadiologyParameterDeleteView.as_view(), name='radiologyparameter-delete'),
    path('api/radiologyparameter/<int:pk>/detail/', RadiologyParameterDetailView.as_view(), name='radiologyparameter-detail'),
    
    path('api/create-bloodbankproducts/', BloodBankProductCreateAPIView.as_view(), name='create_bloodbankproducts'),
    path('api/bloodbankproducts/', BloodBankProductListView.as_view(), name='bloodbankproducts-list'),
    path('api/bloodbankproducts/<int:pk>/', BloodBankProductUpdateView.as_view(), name='bloodbankproducts-update'),
    path('api/bloodbankproducts/<int:pk>/delete/', BloodBankProductDeleteView.as_view(), name='bloodbankproducts-delete'),
    path('api/bloodbankproducts/<int:pk>/detail/', BloodBankProductDetailView.as_view(), name='bloodbankproducts-detail'),
    
    path('api/create-symptomstype/', SymptomsTypeCreateAPIView.as_view(), name='create_symptomstype'),
    path('api/symptomstype/', SymptomsTypeListView.as_view(), name='symptomstype-list'),
    path('api/symptomstype/<int:pk>/', SymptomsTypeUpdateView.as_view(), name='symptomstype-update'),
    path('api/symptomstype/<int:pk>/delete/', SymptomsTypeDeleteView.as_view(), name='symptomstype-delete'),
    path('api/symptomstype/<int:pk>/detail/', SymptomsTypeDetailView.as_view(), name='symptomstype-detail'),
    
    path('api/create-symptomshead/', SymptomsHeadCreateAPIView.as_view(), name='create_symptomshead'),
    path('api/symptomshead/', SymptomsHeadListView.as_view(), name='symptomshead-list'),
    path('api/symptomshead/<int:pk>/', SymptomsHeadUpdateView.as_view(), name='symptomshead-update'),
    path('api/symptomshead/<int:pk>/delete/', SymptomsHeadDeleteView.as_view(), name='symptomshead-delete'),
    path('api/symptomshead/<int:pk>/detail/', SymptomsHeadDetailView.as_view(), name='symptomshead-detail'),
    
    path('api/create-findingcategory/', FindingCategoryCreateAPIView.as_view(), name='create_findingcategory'),
    path('api/findingcategory/', FindingCategoryListView.as_view(), name='findingcategory-list'),
    path('api/findingcategory/<int:pk>/', FindingCategoryUpdateView.as_view(), name='findingcategory-update'),
    path('api/findingcategory/<int:pk>/delete/', FindingCategoryDeleteView.as_view(), name='findingcategory-delete'),
    path('api/findingcategory/<int:pk>/detail/', FindingCategoryDetailView.as_view(), name='findingcategory-detail'),
    
    path('api/create-finding/', FindingCreateAPIView.as_view(), name='create_finding'),
    path('api/finding/', FindingListView.as_view(), name='finding-list'),
    path('api/finding/<int:pk>/', FindingUpdateView.as_view(), name='finding-update'),
    path('api/finding/<int:pk>/delete/', FindingDeleteView.as_view(), name='finding-delete'),
    path('api/finding/<int:pk>/detail/', FindingDetailView.as_view(), name='finding-detail'),
    
    path('api/create-incomehead/', IncomeHeadCreateAPIView.as_view(), name='create_incomehead'),
    path('api/incomehead/', IncomeHeadListView.as_view(), name='incomehead-list'),
    path('api/incomehead/<int:pk>/', IncomeHeadUpdateView.as_view(), name='incomehead-update'),
    path('api/incomehead/<int:pk>/delete/', IncomeHeadDeleteView.as_view(), name='incomehead-delete'),
    path('api/incomehead/<int:pk>/detail/', IncomeHeadDetailView.as_view(), name='incomehead-detail'),
    
    path('api/create-expensehead/', ExpenseHeadCreateAPIView.as_view(), name='create_expensehead'),
    path('api/expensehead/', ExpenseHeadListView.as_view(), name='expensehead-list'),
    path('api/expensehead/<int:pk>/', ExpenseHeadUpdateView.as_view(), name='expensehead-update'),
    path('api/expensehead/<int:pk>/delete/', ExpenseHeadDeleteView.as_view(), name='expensehead-delete'),
    path('api/expensehead/<int:pk>/detail/', ExpenseHeadDetailView.as_view(), name='expensehead-detail'),
    
    path('api/create-leavetype/', LeaveTypeCreateAPIView.as_view(), name='create_leavetype'),
    path('api/leavetype/', LeaveTypeListView.as_view(), name='leavetype-list'),
    path('api/leavetype/<int:pk>/', LeaveTypeUpdateView.as_view(), name='leavetype-update'),
    path('api/leavetype/<int:pk>/delete/', LeaveTypeDeleteView.as_view(), name='leavetype-delete'),
    path('api/leavetype/<int:pk>/detail/', LeaveTypeDetailView.as_view(), name='leavetype-detail'),
    
    path('api/create-department/', DepartmentCreateAPIView.as_view(), name='create_department'),
    path('api/department/', DepartmentListView.as_view(), name='department-list'),
    path('api/department/<int:pk>/', DepartmentUpdateView.as_view(), name='department-update'),
    path('api/department/<int:pk>/delete/', DepartmentDeleteView.as_view(), name='department-delete'),
    path('api/department/<int:pk>/detail/', DepartmentDetailView.as_view(), name='department-detail'),
    
    path('api/create-designation/', DesignationCreateAPIView.as_view(), name='create_designation'),
    path('api/designation/', DesignationListView.as_view(), name='designation-list'),
    path('api/designation/<int:pk>/', DesignationUpdateView.as_view(), name='designation-update'),
    path('api/designation/<int:pk>/delete/', DesignationDeleteView.as_view(), name='designation-delete'),
    path('api/designation/<int:pk>/detail/', DesignationDetailView.as_view(), name='designation-detail'),
    
    path('api/create-specialist/', SpecialistCreateAPIView.as_view(), name='create_specialist'),
    path('api/specialist/', SpecialistListView.as_view(), name='specialist-list'),
    path('api/specialist/<int:pk>/', SpecialistUpdateView.as_view(), name='specialist-update'),
    path('api/specialist/<int:pk>/delete/', SpecialistDeleteView.as_view(), name='specialist-delete'),
    path('api/specialist/<int:pk>/detail/', SpecialistDetailView.as_view(), name='specialist-detail'),
    
    path('api/create-referralcategory/', ReferralCategoryCreateAPIView.as_view(), name='create_referralcategory'),
    path('api/referralcategory/', ReferralCategoryListView.as_view(), name='referralcategory-list'),
    path('api/referralcategory/<int:pk>/', ReferralCategoryUpdateView.as_view(), name='referralcategory-update'),
    path('api/referralcategory/<int:pk>/delete/', ReferralCategoryDeleteView.as_view(), name='referralcategory-delete'),
    path('api/referralcategory/<int:pk>/detail/', ReferralCategoryDetailView.as_view(), name='referralcategory-detail'),
    
    path('api/create-referralcommission/', ReferralCommissionCreateAPIView.as_view(), name='create_referralcommission'),
    path('api/referralcommission/', ReferralCommissionListView.as_view(), name='referralcommission-list'),
    path('api/referralcommission/<int:pk>/', ReferralCommissionUpdateView.as_view(), name='referralcommission-update'),
    path('api/referralcommission/<int:pk>/delete/', ReferralCommissionDeleteView.as_view(), name='referralcommission-delete'),
    path('api/referralcommission/<int:pk>/detail/', ReferralCommissionDetailView.as_view(), name='referralcommission-detail'),
    
    path('api/create-shift/', ShiftCreateAPIView.as_view(), name='create_shift'),
    path('api/shift/', ShiftListView.as_view(), name='shift-list'),
    path('api/shift/<int:pk>/', ShiftUpdateView.as_view(), name='shift-update'),
    path('api/shift/<int:pk>/delete/', ShiftDeleteView.as_view(), name='shift-delete'),
    path('api/shift/<int:pk>/detail/', ShiftDetailView.as_view(), name='shift-detail'),
    
    path('api/create-itemcategory/', ItemCategoryCreateAPIView.as_view(), name='create_itemcategory'),
    path('api/itemcategory/', ItemCategoryListView.as_view(), name='itemcategory-list'),
    path('api/itemcategory/<int:pk>/', ItemCategoryUpdateView.as_view(), name='itemcategory-update'),
    path('api/itemcategory/<int:pk>/delete/', ItemCategoryDeleteView.as_view(), name='itemcategory-delete'),
    path('api/itemcategory/<int:pk>/detail/', ItemCategoryDetailView.as_view(), name='itemcategory-detail'),
    
    path('api/create-itemstore/', ItemStoreCreateAPIView.as_view(), name='create_itemstore'),
    path('api/itemstore/', ItemStoreListView.as_view(), name='itemstore-list'),
    path('api/itemstore/<int:pk>/', ItemStoreUpdateView.as_view(), name='itemstore-update'),
    path('api/itemstore/<int:pk>/delete/', ItemStoreDeleteView.as_view(), name='itemstore-delete'),
    path('api/itemstore/<int:pk>/detail/', ItemStoreDetailView.as_view(), name='itemstore-detail'),
    
    path('api/create-itemsupplier/', ItemSupplierCreateAPIView.as_view(), name='create_itemsupplier'),
    path('api/itemsupplier/', ItemSupplierListView.as_view(), name='itemsupplier-list'),
    path('api/itemsupplier/<int:pk>/', ItemSupplierUpdateView.as_view(), name='itemsupplier-update'),
    path('api/itemsupplier/<int:pk>/delete/', ItemSupplierDeleteView.as_view(), name='itemsupplier-delete'),
    path('api/itemsupplier/<int:pk>/detail/', ItemSupplierDetailView.as_view(), name='itemsupplier-detail'),
    
]
