# Generated by Django 4.0.2 on 2023-07-27 09:57

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_chargecategory_chargetype_taxcategory_charges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None)),
                ('description', models.TextField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('unused', models.BooleanField(default=False)),
                ('bed_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.bedgroup')),
                ('bed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.bedtype')),
            ],
        ),
    ]
