# Generated by Django 4.0.2 on 2023-07-29 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_operationcategory_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=20)),
                ('supplier_contact', models.CharField(max_length=20)),
                ('contact_person_name', models.CharField(max_length=20)),
                ('contact_person_phone', models.CharField(max_length=20)),
                ('drug_license_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.unittype')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineDosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doses', models.ManyToManyField(to='settings.Dose')),
                ('medicine_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.medicinecategory')),
                ('units', models.ManyToManyField(to='settings.Unit')),
            ],
        ),
    ]
