# Generated by Django 4.0.2 on 2023-07-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_dose_medicinecategory_medicinesupplier_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinedosage',
            name='doses',
        ),
        migrations.RemoveField(
            model_name='medicinedosage',
            name='medicine_category',
        ),
        migrations.RemoveField(
            model_name='medicinedosage',
            name='units',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Dose',
        ),
        migrations.DeleteModel(
            name='MedicineDosage',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
