# Generated by Django 4.0.2 on 2023-07-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_remove_medicinedosage_doses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=50)),
                ('medicine_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.medicinecategory')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.unittype')),
            ],
        ),
    ]
