# Generated by Django 4.0.2 on 2023-07-31 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_dosageduration_dosageinterval'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('select', 'Select'), ('component', 'Component'), ('blood group', 'Blood Group')], default='select', max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PathologyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PathologyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RadiologyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RadiologyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bed',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bedgroup',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bedtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chargetype',
            name='chargetype',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='complaintype',
            name='complain_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dosageduration',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dosageinterval',
            name='interval',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicinedosage',
            name='dose',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicinesupplier',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicinesupplier',
            name='contact_person_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicinesupplier',
            name='drug_license_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicinesupplier',
            name='supplier_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='operationcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='purpose',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taxcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='SymptomsHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_head', models.CharField(max_length=100)),
                ('description', models.TimeField()),
                ('symptoms_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.symptomstype')),
            ],
        ),
        migrations.CreateModel(
            name='RadiologyParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('referange_range', models.CharField(max_length=100)),
                ('description', models.TimeField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.radiologyunit')),
            ],
        ),
        migrations.CreateModel(
            name='PathologyParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('referange_range', models.CharField(max_length=100)),
                ('description', models.TimeField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.pathologyunit')),
            ],
        ),
    ]
