# Generated by Django 4.0.2 on 2023-08-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_department_designation_expensehead_findingcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcommission',
            name='ambulance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='bloodbank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='ipd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='opd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='pathology',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='pharmacy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='radiology',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
