# Generated by Django 4.0.2 on 2023-08-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_alter_referralcommission_ambulance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(max_length=100)),
                ('description', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_store_name', models.CharField(max_length=100)),
                ('item_store_code', models.CharField(max_length=100)),
                ('description', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact_person_phone', models.CharField(max_length=100)),
                ('contact_person_email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TimeField()),
            ],
        ),
    ]
