# Generated by Django 4.0.2 on 2023-08-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_itemcategory_itemstore_itemsupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcommission',
            name='ambulance',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='bloodbank',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='ipd',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='opd',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='pathology',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='pharmacy',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='radiology',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
