# Generated by Django 4.0.2 on 2023-08-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_alter_referralcommission_ambulance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathologyparameter',
            name='description',
            field=models.TextField(),
        ),
    ]
