# Generated by Django 4.0.2 on 2023-08-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_alter_pathologyparameter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensehead',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='finding',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incomehead',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itemstore',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itemsupplier',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='radiologyparameter',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='symptomshead',
            name='description',
            field=models.TextField(),
        ),
    ]
